# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DCT.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DCT(object):
    def setupUi(self, DCT):
        DCT.setObjectName("DCT")
        DCT.resize(1072, 767)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        DCT.setFont(font)
        self.label_5 = QtWidgets.QLabel(DCT)
        self.label_5.setGeometry(QtCore.QRect(620, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(DCT)
        self.label_6.setGeometry(QtCore.QRect(100, 261, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(DCT)
        self.textBrowser.setGeometry(QtCore.QRect(10, 290, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(DCT)
        self.pushButton.setGeometry(QtCore.QRect(50, 210, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(DCT)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 135, 172))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.pushButton_2 = QtWidgets.QPushButton(DCT)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 670, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(DCT)
        self.label_7.setGeometry(QtCore.QRect(320, 50, 731, 591))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.layoutWidget.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.textBrowser.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_7.raise_()

        self.retranslateUi(DCT)
        QtCore.QMetaObject.connectSlotsByName(DCT)

    def retranslateUi(self, DCT):
        _translate = QtCore.QCoreApplication.translate
        DCT.setWindowTitle(_translate("DCT", "Dialog"))
        self.label_5.setText(_translate("DCT", "决策树形状"))
        self.label_6.setText(_translate("DCT", "预测结果"))
        self.pushButton.setText(_translate("DCT", "预测"))
        self.label.setText(_translate("DCT", "花萼长度"))
        self.label_2.setText(_translate("DCT", "花萼宽度"))
        self.label_3.setText(_translate("DCT", "花瓣长度"))
        self.label_4.setText(_translate("DCT", "花瓣宽度"))
        self.pushButton_2.setText(_translate("DCT", "生成"))

